### ISSUE TITLE
Find Datasets

### ISSUE THREAD

**Issue by jendiamond** [CodingForProduct/LoveLA#9]
### Data Set Research
I looked through all 403 data sets in LOS ANGELES OPEN DATA and these were the only ones that look potentially interesting. @jendiamond
+ https://data.lacity.org/browse
+ https://data.lacity.org/A-Livable-and-Sustainable-City/What-s-Happening-LA-Calendar-Dataset/d3th-bqdk
+ https://data.lacity.org/A-Livable-and-Sustainable-City/Events-from-LA-Festival-Guide-2014/acy8-72w9
+ https://data.lacity.org/A-Livable-and-Sustainable-City/Library-Branches/a4nt-4gca
+ https://data.lacity.org/A-Livable-and-Sustainable-City/What-s-Happening-LA-Calender-Type-of-Event-Categor/si79-fpzd

**Comment by venetya** [comment]
### LA Metro Links from Wai-Yin's presentation
+ http://www.latimes.com/local/lanow/la-me-ln-bus-ridership-study-20170518-story.html 
+ https://www.metro.net 
+ http://developer.metro.net 
+ https://twitter.com/MetroLosAngeles 
+ http://thesource.metro.net 
+ http://thesource.metro.net/2015/08/05/results-of-metros-latest-customer-survey/ 
+ https://www.metro.net/news/research/

**Comment by venetya** [comment]
### Data Set Research
Found some GTFS data for LA Metro Rails:
#### Routes: 
https://gitlab.com/LACMTA/gtfs_rail/blob/master/routes.txt 

#### Stops: 
https://gitlab.com/LACMTA/gtfs_rail/blob/master/stops.txt 

#### Link to Yelp API documentation and samples
https://www.yelp.com/developers/documentation/v2/examples

#### Ruby Library for handling GTFS data feeds:  
https://github.com/nerdEd/gtfs
